fix aiohttp disconnect error on websockets
aiohttp will throw if the handler doesn't return anything.

```python
14:11:35 aiohttp ERRO Missing return statement on request handler
Traceback (most recent call last):
  File "/Users/steve/conda/envs/port/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 653, in finish_response
    prepare_meth = resp.prepare
                   ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'prepare'
```

https://docs.aiohttp.org/en/stable/web_quickstart.html#websockets
Signed-off-by: Steve Chan <s22chan@hotmail.com>